refactor: CI/CD

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -36,26 +36,27 @@ jobs:
     runs-on: ubuntu-latest
     needs: test
     if: github.ref == 'refs/heads/develop'
-
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Set up SSH key
-        uses: webfactory/ssh-agent@v0.9.0
+      - name: SSH Action
+        uses: appleboy/ssh-action@v1.0.3
         with:
-          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
-
-      - name: Deploy to server
-        run: |
-          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOSTNAME }} << 'EOF'
+          host: ${{ secrets.SSH_HOSTNAME }}
+          username: ${{ secrets.SSH_USERNAME }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          script: |
             cd ~/wink-official-backend
-          
+            
+            if [ ! -f "./deploy/config/backend.env" ]; then
+              echo "Error: $FILE does not exist."
+              exit 1
+            fi
+            
+            if [ "$(git rev-parse --abbrev-ref HEAD)" != "develop" ]; then
+              git checkout develop
+            fi
+            
             git pull origin develop
-          
-            echo "${{ secrets.CICD_DOCKER_ENV }}" > cicd.docker.env
-          
-            docker compose build
+            
+            docker compose pull
             docker compose down
             docker compose up -d
-          EOF
