refactor: Auth 및 기타 코드 리팩토링 (#18)
* chore: automock 라이브러리 추가

* refactor: import order

* refactor: redis 반환값 수정

* refactor: 레포지토리에서 모든 케이스 처리

* refactor: DI시 필드 이름 통일

* refactor: configService에서 값 가져올 때 없을 경우 throw

* refactor: import order 정리

* refactor: 테스트시 사용되는 mocking 전용 유틸 함수 추가

* refactor: package.json의 peerDependencies 정리

* refactor: tsconfig.json

* refactor: Dockerfile

* refactor: utils import order

* refactor: tsconfig.json

* refactor: test action

* refactor: Actions에 yarn 패키지 캐싱

* refactor: CI/CD

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -13,7 +13,6 @@ concurrency:
 jobs:
   test:
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -22,9 +21,13 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: '20'
+          cache: 'yarn'
 
-      - name: Install dependencies
-        run: yarn install
+      - name: Get yarn cache directory
+        uses: c-hive/gha-yarn-cache@v2
+
+      - name: Install packages
+        run: yarn install --frozen-lockfile
 
       - name: Run tests
         run: yarn test
@@ -33,26 +36,27 @@ jobs:
     runs-on: ubuntu-latest
     needs: test
     if: github.ref == 'refs/heads/develop'
-
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Set up SSH key
-        uses: webfactory/ssh-agent@v0.9.0
+      - name: SSH Action
+        uses: appleboy/ssh-action@v1.0.3
         with:
-          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
-
-      - name: Deploy to server
-        run: |
-          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOSTNAME }} << 'EOF'
+          host: ${{ secrets.SSH_HOSTNAME }}
+          username: ${{ secrets.SSH_USERNAME }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          script: |
             cd ~/wink-official-backend
-          
+            
+            if [ ! -f "./deploy/config/backend.env" ]; then
+              echo "Error: $FILE does not exist."
+              exit 1
+            fi
+            
+            if [ "$(git rev-parse --abbrev-ref HEAD)" != "develop" ]; then
+              git checkout develop
+            fi
+            
             git pull origin develop
-          
-            echo "${{ secrets.CICD_DOCKER_ENV }}" > cicd.docker.env
-          
-            docker compose build
+            
+            docker compose pull
             docker compose down
             docker compose up -d
-          EOF
